os: linux
dist: xenial
branches:
  only:
    - master
before_install:
  - sudo apt-get update --quiet
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - poetry install -v
script:
  - poetry run pytest --verbose
notifications:
  email:
    on_success: change
    on_failure: always
